version: "3"

networks:
 scan-api:
   external: false

services:
  scan-stats-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scan-stats-api
    ports:
      - "${PORT}:${PORT}"
    networks:
      - scan-api
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - PORT=${PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  postgres:
    image: postgres:14.2-alpine
    container_name: scan-stats-database
    networks:
      - scan-api
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - scan-pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  scan-pgdata:
    external: false
